name: PR Check

on:
  pull_request:
    types:
      - opened

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR count
        id: pr-count
        run: |
          PR_COUNT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/naturalcrit/homebrewery/pulls? state=open&head=${{ github.actor }}:${{ github.head_ref }}" | jq '. | length')
          echo "::set-output name=pr_count::$PR_COUNT"

      - name: Update PR description
        if: ${{ steps.pr_count.outputs.pr_count }} -ge 1
        run: |
          gh pr edit ${{ github.event.number }} --body "You already have ${{ steps.pr-count.outputs.pr_count }} PRs open. Consider completing some of your existing PRs before opening new ones."
